### ISSUE TITLE
CGContextSetBlendMode: invalid context 0x0

### ISSUE THREAD

**Issue by oodavid** [gameclosure/native-android#16]
After building a game and testing on my device I get some serious looking errors on ADB Monitor (maybe 100 or so on my game)

Build with `devkit release native-android --enableReleaseLogging`

Error looks like: `<Error>: CGContextSetBlendMode: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.`

I'm not 100% sure that this is a native-android issue or elsewhere as I couldn't find CGContextSetBlendMode anywhere in the native-android directory.

**Comment by jwilm** [comment]
CGContext is part of the iOS CoreGraphics framework. I am not sure how these logs showed up in your android build.

**Comment by mgh** [comment]
This is an iOS issue, closing here. Most likely the same as https://github.com/gameclosure/native-ios/issues/30.
