### ISSUE TITLE
Google Play Warnings: Native android is running an outdated version of OpenSSL

### ISSUE THREAD

**Issue by tuanna222** [gameclosure/native-android#17]
Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered “dangerous products” and subject to removal from Google Play.

Debug:
$ strings libgcypto.so | grep "^OpenSSL"
OpenSSLDie
OpenSSL_add_all_ciphers
OpenSSL_add_all_digests
OpenSSL 1.0.0e 6 Sep 2011

**Comment by rampr** [comment]
This issue has again been reported by google, asking us to upgrade to OpenSSL 1.02f/1.01r.

The one in the build is 1.0.1j

**Comment by rampr** [comment]
@martell ^
