### ISSUE TITLE
Update V8 to latest trunk revision

### ISSUE THREAD

**Issue by amerkoleci** [gameclosure/native-android#2]
Hi,
Would be possible to update Google V8 to latest trunk version, i'm using the same code and its different for current desktop and yours Android version.

For example i can't do:
HandleScope scope(_isolate);

Thanks

**Comment by martell** [comment]
The new tealeaf project will have a version that is much newer and up to date.
Currently we use spider-monkey over v8.
Please follow here when it is available shortly if you want.
https://github.com/gameclosure/tealeaf
