### ISSUE TITLE
Can not build native-android with other minSdkVersion

### ISSUE THREAD

**Issue by tuanna222** [gameclosure/native-android#21]
Devkit2 should support to change minSdkVersion and targetSdkVersion when building.
Ex:
devkit release native-android --minsdkversion 19 --targetsdkversion 21

**Comment by jwilm** [comment]
What is the reason for this? As a developer, you should be trying to support the lowest minsdkversion as possible to access more devices.

**Comment by mgh** [comment]
I can see a use-case if you're developing a plugin that has a higher min-sdk version.
