### ISSUE TITLE
Devkit release native-android not worked on windows 8 system

### ISSUE THREAD

**Issue by rawatrob** [gameclosure/native-android#23]
Hi 
I have build a test file by the below command
Devkit release native-android 
but it not build .apk it just show

  [ndk-build]    ndk-build -j 8 DEBUG=1

and finished the script..
so can you tell me where is the issues 
I have also do some r&n on build.js file in native-android but didn't get any success I have also delete -TeaLeaf folder but didn't get any error this again show me same thing
[ndk-build]    ndk-build -j 8 DEBUG=1
and finished the script..

in the build.js have a function

function buildSupportProjects(api, opts, cb) {
  var f = ff(this, function() {
    if (opts.clean || opts.arch) {
      spawnWithLogger(api, 'make', ['clean'], {cwd: __dirname}, f.slot());
    }
  }, function() {
    var args = ["-j", "8", (opts.debug ? "DEBUG=1" : "RELEASE=1")];
    if (opts.arch) {
      args.push('APP_ABI=' + opts.arch);
    }
    spawnWithLogger(api, 'ndk-build', args , { cwd: path.join(__dirname, "TeaLeaf") }, f.wait());
  }).cb(cb);
}

in this function have a line 

spawnWithLogger(api, 'ndk-build', args , { cwd: path.join(__dirname, "TeaLeaf") }, f.wait());
I thing it stop the "args"
logger.log("Rawat File----------"+args);
bcz when I print it then I got the same  line 
[ndk-build]    ndk-build -j 8 DEBUG=1

so please check it and help me

**Comment by mgh** [comment]
This was addressed in our mailing list.
