### ISSUE TITLE
Fix missing core symlink

### ISSUE THREAD

**Issue by jwilm** [gameclosure/native-android#27]
There is supposed to be a symlink named `core` in `TeaLeaf/jni/` which points to `native-core`. The submodule `native-core` should just be moved there instead since it's not used anywhere else.

**Comment by mgh** [comment]
This sounds like a failed `npm install`?

`npm postinstall` runs `make setup && make clean || true` which creates the symlink.  I think we don't catch any errors here in case the user hasn't installed the android sdk.

**Comment by mgh** [comment]
Fixed in https://github.com/gameclosure/native-android/commit/79ae4d7b33650bcaa116ba36112aa3aca3d5fc1e.
