### ISSUE TITLE
Is full screen mode for native android app configurable?

### ISSUE THREAD

**Issue by niranjan-borawake** [gameclosure/native-android#34]
Hello GC team,

The flag set in `TeaLeaf.java` [here](https://github.com/gameclosure/native-android/blob/master/TeaLeaf/src/com/tealeaf/TeaLeaf.java#L636) forces the app to run in full-screen mode (meaning hides the status bar at the top) by default. 
Is this configurable?

I need to keep the status bar visible all the time.

The above mentioned code overrides if I try to set this feature from manifest.xml.

Thanks.

**Comment by martell** [comment]
closing as the PR was merged
