### ISSUE TITLE
Illegal Argument Exception in OpenGl

### ISSUE THREAD

**Issue by rampr** [gameclosure/native-android#9]
There is a reported problem and the fix here - http://stackoverflow.com/questions/12855103/eglcreatewindowsurface-fails-with-java-lang-illegalargumentexception

I've not been able to reproduce, but we see crash reports(provided by amazon) in Kindle 2nd Generation devices on our games

**Comment by mgh** [comment]
This was fixed a few days later in https://github.com/gameclosure/native-android/commit/59b7c612d42b195c8d1ddc229afa252996a542d4 but this issue was never closed.  Closing now!
